name: Node.js CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --non-interactive --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: yarn lint
      - run: yarn build
      - run: yarn test:coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          flags: unittests
          name: graph-studio-billing-contracts
          fail_ci_if_error: true
